# Form implementation generated from reading ui file 'E:\QTDESIGN\K234112E\chap6\TichHopChart\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 663)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonBarChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBarChart.setGeometry(QtCore.QRect(20, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonBarChart.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\QTDESIGN\\K234112E\\chap6\\TichHopChart\\ui\\../images/ic_barchart.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBarChart.setIcon(icon)
        self.pushButtonBarChart.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBarChart.setObjectName("pushButtonBarChart")
        self.pushButtonPieChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPieChart.setGeometry(QtCore.QRect(180, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonPieChart.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\QTDESIGN\\K234112E\\chap6\\TichHopChart\\ui\\../images/ic_piechart.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPieChart.setIcon(icon1)
        self.pushButtonPieChart.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonPieChart.setObjectName("pushButtonPieChart")
        self.pushButtonLineChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLineChart.setGeometry(QtCore.QRect(340, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLineChart.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:\\QTDESIGN\\K234112E\\chap6\\TichHopChart\\ui\\../images/ic_linechart.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLineChart.setIcon(icon2)
        self.pushButtonLineChart.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonLineChart.setObjectName("pushButtonLineChart")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(570, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonExit.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:\\QTDESIGN\\K234112E\\chap6\\TichHopChart\\ui\\../images/ic_shutdown.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon3)
        self.pushButtonExit.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 691, 501))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutPlot = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlot.setObjectName("verticalLayoutPlot")
        self.verticalLayout_2.addLayout(self.verticalLayoutPlot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BanhBeo"))
        self.pushButtonBarChart.setText(_translate("MainWindow", "Bar Chart"))
        self.pushButtonPieChart.setText(_translate("MainWindow", "Pie Chart"))
        self.pushButtonLineChart.setText(_translate("MainWindow", "Line Chart"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.groupBox.setTitle(_translate("MainWindow", "Chart Visualization:"))
