from chap2.ex28.lib28 import convert_str_to_int, print_arr_perline, get_even_digits, negative_digits, prime_digits

s = input('nhap chuoi la cac so co ngan cach [;]: ')
arr_str = s.split(';')
arr_int = convert_str_to_int(arr_str)
print_arr_perline(arr_int)
print('avg =', sum(arr_int)/len(arr_int))
arr_int_even = get_even_digits(arr_int)
print('-'*30)
print('even digits: ')
print_arr_perline(arr_int_even)
print('count =', len(arr_int_even))
print('avg =', sum(arr_int_even)/len(arr_int_even))
print('-'*30)
print('\nnegative digits: ')
arr_int_negative = negative_digits(arr_int)
print_arr_perline(arr_int_negative)
print('avg =', sum(arr_int_negative)/len(arr_int_even))
print('-'*30)
print('\nprime digits: ')
arr_int_prime = prime_digits(arr_int)
print_arr_perline(arr_int_prime)
print('avg =', sum(arr_int_prime)/len(arr_int_prime))
print('-'*30)
